language: node_js
node_js:
- 8.9.1
sudo: false
before_install:
- npm install hexo-cli -g
install:
- npm install
branches:
  only:
  - master
before_script:
- git config --global user.name 'anbuchelva'
- git config --global user.email 'anbuchelva@gmail.com'
- sed -i'' "s~git@github.com:anbuchelva/blog.git~https://${GH_TOKEN}:x-oauth-basic@github.com/anbuchelva/blog.git~"
  _config.yml
script:
- git submodule init
- git submodule update
- cd themes/tranquilpeak
- NODE_ENV=development npm install
- npm install grunt-cli -g
- npm install bower -g
- bower install
- grunt buildProd
- cd ..
- hexo clean
- hexo algolia
- hexo generate
- hexo deploy
- echo "deployment successful!!"
