version: 2
jobs:
  build:  
    docker:
      - image: circleci/node:8.9.1
    branches:
      only:
        - master
      ignore:
        - gh-pages
    working_directory: ~/temp
    steps:
      - checkout
      - run: sudo npm install -g hexo-cli
      - run: sudo npm install -g grunt-cli
      - run: git submodule init
      - run: git submodule update
      - run: git config --global user.name ${GIT_USER_NAME}
      - run: git config --global user.email ${GIT_USER_EMAIL}
      - restore_cache:
          key: x-cache-{{ checksum "package.json" }}
      - restore_cache:
          key: y-cache-{{ checksum "./themes/tranquilpeak/package.json" }}
      - run: sudo npm install
      - run: cd themes/tranquilpeak && NODE_ENV=development npm install
      - save_cache:
          key: x-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - save_cache:
          key: y-cache-{{ checksum "./themes/tranquilpeak/package.json" }}
          paths:      
            - ./themes/tranquilpeak/node_modules
      - run: cd themes/tranquilpeak && sudo npm install grunt-cli -g
      - run: cd themes/tranquilpeak && sudo npm install bower -g
      - run: cd themes/tranquilpeak && bower install
      - run: cd themes/tranquilpeak && grunt buildProd
      - run: hexo clean
      - run: hexo algolia
      - run: hexo generate
      - run: hexo deploy
